branch-defaults:
  master:
    environment: 00noderune-env
  develop:
    environment: 00noderune-env
global:
  application_name: 00noderune
  default_platform: 64bit Amazon Linux/4.6.0
  default_region: us-east-2
  sc: git
