# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10
      user: root
    steps:
      - run:
          name: Install yarn
          command: npm i -g yarn
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

