# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/rune
    docker:
      - image: circleci/node:10
        user: root
    steps:
      - run:
          name: Install yarn
          command: npm i -g yarn
      - run:
          name: Install pip and awsebcli
          command: |
            apt-get update && apt-get install -y python-pip python-dev
            sudo -H pip install awsebcli --upgrade --ignore-installed
            echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: TSLint check
          command: yarn tslint
      - run:
          name: Types check
          command: yarn tsc
      - run:
          name: Deploying to dev env
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ];
            then
              eb deploy
            fi
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
