# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/rune
    docker:
      - image: circleci/node:10
        user: root
    steps:
      - run:
          name: Install yarn
          command: npm i -g yarn
      - run:
          name: Install pip and awscli
          command: |
            apt-get update && apt-get install -y python-pip python-dev
            sudo -H pip install awsebcli==3.7.4 --upgrade --ignore-installed
            echo 'export PATH=~/.local/bin/:$PATH' >> $BASH_ENV
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: TSLint check
          command: yarn tslint
      - run:
          name: Types check
          command: yarn tsc
      - run:
          name: Build
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              ARCHIVE_TAG=sha-${CIRCLE_SHA1::7};
            else
              ARCHIVE_TAG=${CIRCLE_TAG};
            fi
            yarn build
            tar -czf ${ARCHIVE_TAG}.tar.gz dist/
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
#  deploy:
#    working_directory: ~/rune
#    docker:
#      - image: circleci/node:10
#        user: root
#    steps:
#      - run:
#          name: Install pip and eb cli
#          command: |
#            apt-get update && apt-get install -y python-pip python-dev
#


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
#      - deploy:
#          requires:
#            - build
