version: 2.1
jobs:
  build:
    working_directory: /opt/build
    docker:
      - image: circleci/node:10.12
    steps:
      - run:
          name: Install yarn
          command: |
            npm i -g yarn

workflows:
  version: 2
  build:
    jobs:
      - build

