# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
    - image: circleci/node:10
      user: root
    steps:
      - run:
          name: Install yarn
          command: npm i -g yarn
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache
      - run:
          name: Install packages
          command: yarn install
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
  deploy:


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build

