# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    working_directory: ~/rune
    docker:
    - image: circleci/node:10
      user: root
    steps:
      - run:
          name: Install yarn
          command: npm i -g yarn
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-cache
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              ARCHIVE_TAG=sha-${CIRCLE_SHA1::7};
            else
              ARCHIVE_TAG=${CIRCLE_TAG};
            fi
            yarn build
            tar -czf ${ARCHIVE_TAG}.tar.gz build/
      - save_cache:
          key: yarn-packages-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
